version: "3.3"

services:
  telegram_media_downloader:
    image: telegram_media_downloader_enhanced:latest
    build: .
    ports:
      - "5000:5000"
    volumes:
      - "./downloads/:/app/downloads/"
      - "$HOME/.config/rclone/:$HOME/.config/rclone/"
      - "./config.yaml:/app/config.yaml"
      - "./data.yaml:/app/data.yaml"
      - "./log/:/app/log/"
      - "./sessions/:/app/sessions"
      - "./temp/:/app/temp"
    restart: "unless-stopped"