version: "3.3"

services:
  telegram_media_downloader:
    image: telegram_media_downloader_enhanced:latest
    build: .
    ports:
      - "5001:5000"
    environment:
      - RCLONE_CONFIG=/root/.config/rclone/rclone.conf
    volumes:
      - "./downloads/:/app/downloads/"
      - "$HOME/.config/rclone/:/root/.config/rclone/"
      - "./config.yaml:/app/config.yaml"
      - "./data.yaml:/app/data.yaml"
      - "./log/:/app/log/"
      - "./sessions/:/app/sessions"
      - "./temp/:/app/temp"
    restart: "unless-stopped"
